In [42]:
import numpy as np

## **Создание массивов**

In [43]:
# Создание массива из обычного списка
a = np.array([1, 2, 3, 4])

# Создание двумерного массива из списка списков
b = np.array([[1, 2, 3],
              [4, 5, 6]])

# Создание массива zeros
z = np.zeros((2, 3))

# Создание массива с шагом с помощью arange
r = np.arange(0, 10, 2)

a, b, z, r


(array([1, 2, 3, 4]),
 array([[1, 2, 3],
        [4, 5, 6]]),
 array([[0., 0., 0.],
        [0., 0., 0.]]),
 array([0, 2, 4, 6, 8]))

## **shape и dtype**

In [44]:
# Получение shape и dtype у массива b
b_shape = b.shape
b_dtype = b.dtype

b_shape, b_dtype


((2, 3), dtype('int64'))

## **Индексирование и срез**

In [45]:
# Получение отдельного элемента из двумерного массива
elem = b[1, 2]  # элемент второй строки, третьего столбца

# Получение среза
sub = b[:, 1:]  # все строки, столбцы начиная со второго

elem, sub


(np.int64(6),
 array([[2, 3],
        [5, 6]]))

## **Векторные** **операции**

In [46]:
# Создание двух массивов для операций
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])

# Поэлементное сложение и умножение
sum_xy = x + y
prod_xy = x * y

sum_xy, prod_xy


(array([11, 22, 33]), array([10, 40, 90]))

## **Простая статистика**

In [47]:
# Вычисление средней величины и других статистик
mean_b = np.mean(b)
min_b = np.min(b)
max_b = np.max(b)

mean_b, min_b, max_b


(np.float64(3.5), np.int64(1), np.int64(6))